swagger: "2.0"
info:
  version: "0"
  title: WebWallet API
host: localhost
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /address:
    x-swagger-router-controller: endpoints
    post:
      description: Generates and returns a new wallet address.
      operationId: address.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /currency:
    x-swagger-router-controller: endpoints
    post:
      description: Creates a new digital currency.
      operationId: currency.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  
  /transaction:
    x-swagger-router-controller: endpoints
    post:
      description: Creates or updates a transaction request.
      operationId: transaction.post
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
